apiVersion: apps/v1
kind: Deployment
metadata:
  name: games-service
  labels:
    app: games-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: games-service
  template:
    metadata:
      labels:
        app: games-service
    spec:
      containers:
      - name: games-service
        image: kofolmarko/games-service:latest
        ports:
        - containerPort: 8001
        envFrom:
        - secretRef:
            name: games-service-secrets