name: Deploy Microservice to Kubernetes

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    # - name: Log in to Docker Hub
    #   uses: docker/login-action@v2
    #   with:
    #     username: ${{ secrets.DOCKER_USERNAME }}
    #     password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      run: |
        docker build -t kofolmarko/games-service .
        docker tag kofolmarko/games-service:latest kofolmarko/games-service:latest
        docker push kofolmarko/games-service:latest

    - name: Set up kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'latest'

    - name: Authenticate with Kubernetes
      env:
        KUBECONFIG: ${{ secrets.KUBECONFIG }}
      run: |
        echo "$KUBECONFIG" > kubeconfig
        export KUBECONFIG=kubeconfig
        kubectl cluster-info

    - name: Apply Kubernetes Secret
      run: |
        kubectl create secret generic my-microservice-secrets \
          --from-literal=SUPABASE_URL=${{ secrets.SUPABASE_URL }} \
          --from-literal=SUPABASE_KEY=${{ secrets.SUPABASE_KEY }}

    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f k8s/
        kubectl rollout status deployment/games-service
