name: Deploy Microservice to Kubernetes

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: azure

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      run: |
        docker build -t kofolmarko/games-service .
        docker tag kofolmarko/games-service:latest kofolmarko/games-service:latest
        docker push kofolmarko/games-service:latest

    - name: Set up kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'latest'

    - name: Authenticate with Kubernetes
      uses: actions-hub/kubectl@master
      env:
        KUBE_CONFIG: ${{ secrets.KUBECONFIG }}
      with:
        args: get pods

    - name: Debug Kubernetes Cluster Connection
      run: |
        kubectl get nodes
        kubectl get namespaces

    - name: Debug Secrets
      run: |
        echo "SUPABASE_URL is set: ${ { secrets.SUPABASE_URL }+yes }"
        echo "SUPABASE_KEY is set: ${ { secrets.SUPABASE_KEY }+yes }"

    - name: Apply Kubernetes Secret
      run: |
        kubectl create secret generic games-service-secrets \
          --from-literal=SUPABASE_URL=${{ secrets.SUPABASE_URL }} \
          --from-literal=SUPABASE_KEY=${{ secrets.SUPABASE_KEY }}

    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f k8s/
        kubectl rollout status deployment/games-service
