name: Deploy Microservice to Kubernetes

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: azure
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      run: |
        docker build -t kofolmarko/games-service .
        docker push kofolmarko/games-service:latest

    - name: Set up Kubeconfig
      run: |
        echo "${{ secrets.KUBE_CONFIG }}" | base64 -d > kubeconfig
        export KUBECONFIG=$(pwd)/kubeconfig
      env:
        KUBECONFIG: ${{ secrets.KUBE_CONFIG }}

    # - name: Apply Kubernetes Secret
    #   run: |
    #     kubectl delete secret games-service-secrets || true
    #     kubectl create secret generic games-service-secrets \
    #       --from-literal=SUPABASE_URL=$SUPABASE_URL \
    #       --from-literal=SUPABASE_KEY=$SUPABASE_KEY
    #   env:
    #     SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
    #     SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}

    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f k8s/
        kubectl rollout status deployment/games-service
